version: "3.9"
services:
  backend: 
    build: backend
    ports: 
      - "5001:5001"
    environment:
      EVERNOTE_TOKEN: "${EVERNOTE_TOKEN}"
  frontend:
    build: frontend
    ports: 
      - "8080:8080"
    environment:
      REACT_APP_EVERNOTE_SERVER_HOST: "localhost"
      REACT_APP_EVERNOTE_SERVER_PORT: "5001"
