version: "0.0.0"
services:
  backend: 
    build: backend
    ports: 
      - "5000:5001"
    environment:
      EVERNOTE_TOKEN: "${EVERNOTE_TOKEN}"
  frontend:
    build: frontend
    ports: 
      - "8080:8080"
    environment:
      EVERNOTE_API_ENDPOINT: "${EVERNOTE_API_ENDPOINT}"
      DB_CONNECTION_NAME: "${DB_CONNECTION_NAME}"
      DB_ENDPOINT: "${DB_ENDPOINT}"
      EVERNOTE_USER_ID: "${EVERNOTE_USER_ID}"
      EVERNOTE_SHARD_ID: "${EVERNOTE_SHARD_ID}"
  mysql:
    image: armv7/armhf-mysql:5.5.44
    volumes:
      - ./data/mysql/datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
